#!/usr/bin/bash

export THREADS=8
export TIME_PROBE=60
export TIME_ADJUST=120
export TIME_SOLVE=120

export CMD="\
-threads $THREADS \
-time-probe $(($TIME_PROBE * 1000)) \
-time-adjust $(($TIME_ADJUST * 1000)) \
-time-solve $(($TIME_SOLVE * 1000)) "

export DIR="$HOSTNAME-$THREADS-$TIME_PROBE-$TIME_ADJUST-$TIME_SOLVE"

mkdir -p logs/$DIR

export BENCH="\
  abz5 abz6 abz7 abz8 \
  abz9 ft06 ft10 ft20 \
  la01 la02 la03 la04 \
  la05 la06 la07 la08 \
  la09 la10 la11 la12 \
  la13 la14 la15 la16 \
  la17 la18 la19 la20 \
  la21 la22 la23 la24 \
  la25 la26 la27 la28 \
  la29 la30 la31 la32 \
  la33 la34 la35 la36 \
  la37 la38 la39 la40 \
  orb01 orb02 orb03 orb04 \
  orb05 orb06 orb07 orb08 \
  orb09 orb10 swv01 swv02 \
  swv03 swv04 swv05 swv06 \
  swv07 swv08 swv09 swv10 \
  swv11 swv12 swv13 swv14 \
  swv15 swv16 swv17 swv18 \
  swv19 swv20 yn1 yn2 \
  yn3 yn4 tai-15-15-0 tai-15-15-1 \
  tai-15-15-2 tai-15-15-3 tai-15-15-4 tai-15-15-5 \
  tai-15-15-6 tai-15-15-7 tai-15-15-8 tai-15-15-9 \
  tai-20-15-0 tai-20-15-1 tai-20-15-2 tai-20-15-3 \
  tai-20-15-4 tai-20-15-5 tai-20-15-6 tai-20-15-7 \
  tai-20-15-8 tai-20-15-9 tai-20-20-0 tai-20-20-1 \
  tai-20-20-2 tai-20-20-3 tai-20-20-4 tai-20-20-5 \
  tai-20-20-6 tai-20-20-7 tai-20-20-8 tai-20-20-9"


for tbf in 0.0 0.1 0.25; do
  for h in afc action chb; do
    for b in $BENCH; do
       ./examples/job-shop.exe -branching $h -tbf $tbf $b \
	| tee $DIR/$b-$h-$tbf.log 
    done
  done
done
